eno=int(input("enter empolyee no:"))
ename=input("enter empolyee name:")
esal=float(input("enter empolyee salary:"))
eadd=input("enter empolyee address:")
emarried=bool(input("enter empolyee mararied ? [True|Flase]:"))
print("employee No",eno)
print("employee Name",ename)
print("employee sal",esal)
print("employee add",eadd)
print("employee married ?",emarried)